### ISSUE TITLE
Code crashes when it tries to write a file in a non existing directory

### ISSUE THREAD

**Issue by alucchi** [dalab/dissolve-struct#25]
Code crashes when it tries to write a file in a non existing directory. Shall we create the directory instead?

Exception in thread "main" java.io.FileNotFoundException: ../Results/true_true_Coursera_CoCoa_viterbi_chain_pairwise-1440841761677.csv (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:110)
	at java.io.FileWriter.<init>(FileWriter.java:63)
	at ch.ethz.dalab.dissolve.classification.StructSVMWithDBCFW.trainModel(StructSVMWithDBCFW.scala:27)

**Comment by martinjaggi** [comment]
the path
solverOptions.debugInfoPath
should always be set to debug/, that directory is there.
do we have to change the parameter in some of the examples?

(if adding empty directories, need to write them explicitly in .gitignore)
